# .sops.yaml
keys:
  - &joe_personal age1qlqz7phpfhtvluq4dqq8yqghux4vvxqfze50k9tqr498cynmqqxq9n76xw
  - &strix_host age1s002ten38mn9c7xqu3hkvnxwc0crmuvu9cat2dn2luvnu8hch3jsyv3jdr

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *joe_personal
        - *strix_host